package com.fsck.k9.mail.e3;

import com.google.common.base.Function;

import java.security.KeyStore;

/**
 * Function for converting a subject to an alias used for {@link E3KeyStoreService}.
 *
 * Created on 12/12/2017.
 *
 * @author koh
 */

public class E3AliasFunction implements Function<String, String> {
    private String aliasFormat = "%s E3 Key";

    /**
     * Generate the standard alias used in the {@link KeyStore}s generated by this class for a
     * given subject.
     *
     * @param subject X509 Subject, usually email.
     * @return The subject converted to the alias used in {@link KeyStore}s produced by this class.
     */
    @Override
    public String apply(final String subject) {
        return String.format(aliasFormat, subject);
    }
}
